(function(){
let marketingMode='calendar', marketingMonth=new Date().getMonth()+1;
const baseProjectView=projectView;
const recoveredMarketingData={"headers":["구분","순서","제목","설명","담당","마감일","상태","표시","자료 링크"],"rows":[["캘린더","1","징안점 오픈 사전 안내","OPEN · 상하이 징안에서 만나는 VELYB","사진","2026-09-28","예정","TRUE"],["캘린더","2","한국 VELYB 브랜드 티징","한국에서 축적한 VELYB 브랜드 경쟁력 소개","사진","2026-09-29","예정","TRUE"],["캘린더","3","한국 VELYB 브랜드 티징","한국 브랜드에서 징안점 오픈으로 연결되는 티징","영상","2026-09-30","예정","TRUE","https://drive.google.com/file/d/1l3jTYeMfmsISmsodu4fWPoB0lqU9u9K0/view?usp=drive_link"],["캘린더","4","징안점 오픈 소개","징안점 오픈을 알리는 간단한 소개 영상","영상","2026-10-02","예정","TRUE"],["캘린더","5","정보성 컨텐츠","수분·피부결·톤·탄력 등 목표별 관리 포인트","사진","2026-10-03","예정","TRUE"],["캘린더","6","징안점 컨텐츠","브랜드 가림막 오픈 준비 알림","사진","2026-10-04","예정","TRUE"],["캘린더","7","한국 블리비 모습 소개","명동점 또는 청담점 실제 분위기 영상","영상","2026-10-05","예정","TRUE"],["캘린더","8","정보성 컨텐츠","얼굴형별 리프팅 포인트","사진","2026-10-07","예정","TRUE"],["캘린더","9","징안점 컨텐츠 ","인테리어 영상","사진","2026-10-09","예정","TRUE"],["캘린더","10","실장 인터뷰 ①","Q&A","영상","2026-10-12","예정","TRUE"],["캘린더","11","정보성 컨텐츠","연령대별 고민 포인트와 관리 방향","사진","2026-10-14","예정","TRUE"],["캘린더","12","정보성 컨텐츠","한국에서 피부과 가면 많이 묻는 질문","사진","2026-10-16","예정","TRUE"],["캘린더","13","실장 인터뷰 ②","Q&A","영상","2026-10-19","예정","TRUE"],["캘린더","14","정보성 컨텐츠","피지·탄력·흉터 등 원인별 관리 방향","사진","2026-10-21","예정","TRUE"],["캘린더","15","정보성 컨텐츠","레이저·리프팅·주사 시술 후 기본 주의사항","사진","2026-10-23","예정","TRUE"],["캘린더","16","징안점 위치·찾아가는 방법","실제 동선 중심 위치 안내","영상","2026-10-26","확인 필요","TRUE"],["캘린더","17","징안점 오픈 예정 안내","위치·예약 채널 사전 안내","사진","2026-10-28","예정","TRUE"],["캘린더","18","징안점 주요 시술 미리보기","확정 시술 카테고리 선공개","사진","2026-10-30","미정","TRUE"],["캘린더","19","징안점 오픈 카운트다운","오픈 일정과 핵심 정보 안내","영상","2026-11-02","예정","TRUE"],["캘린더","20","오픈 이벤트·혜택","이벤트 및 방문 혜택 안내","사진","2026-11-04","미정","TRUE"],["캘린더","21","사전예약 혜택","사전예약 방법 및 혜택 안내","사진","2026-11-06","미정","TRUE"]]};
window.marketingContentSource=function(data){
 const valid=d=>d&&!d.error&&Array.isArray(d.headers)&&Array.isArray(d.rows);
 const kind=d=>d.headers.findIndex(h=>String(h).trim()==='구분');
 if(valid(data)&&data.rows.some(r=>String(r[kind(data)]||'').trim()==='캘린더'))return {data,recovered:false};
 return {data:recoveredMarketingData,recovered:true};
};
function marketingRecords(data){if(!data)return[];if(!Array.isArray(data.headers)||!Array.isArray(data.rows))return [];const h=data.headers;const idx=n=>h.findIndex(x=>String(x).trim()===n);return data.rows.map(r=>({kind:String(r[idx('구분')]||'').trim(),order:Number(r[idx('순서')]||999),title:String(r[idx('제목')]||''),detail:String(r[idx('설명')]||''),form:String(r[idx('담당')]||''),date:String(r[idx('마감일')]||'').trim().slice(0,10),status:String(r[idx('상태')]||''),show:idx('표시')<0||checked(r[idx('표시')])})).filter(x=>x.show)}
function calendarHTML(records,month){const year=2026,first=new Date(year,month-1,1),last=new Date(year,month,0),start=(first.getDay()+6)%7;let cells='';for(let i=0;i<start;i++)cells+='<div class="mcal-cell muted"></div>';for(let d=1;d<=last.getDate();d++){const iso=year+'-'+String(month).padStart(2,'0')+'-'+String(d).padStart(2,'0'),items=records.filter(x=>x.kind==='캘린더'&&x.date===iso);cells+='<div class="mcal-cell"><b>'+d+'</b>'+items.map(x=>'<div class="mcal-item"><small>'+esc(x.form||'콘텐츠')+'</small><strong>'+esc(x.title)+'</strong></div>').join('')+'</div>'}return '<div class="mcal-head"><button data-month="prev">‹</button><h2>'+year+'년 '+month+'월 콘텐츠 캘린더</h2><button data-month="next">›</button></div><div class="mcal-week">'+['월','화','수','목','금','토','일'].map(x=>'<b>'+x+'</b>').join('')+'</div><div class="mcal-grid">'+cells+'</div>'}
function weekName(date){const m=Number(date.slice(5,7)),d=Number(date.slice(8,10));if(m===9)return'9월 마지막 주';if(m===11)return'11월 1주차';return d<=4?'10월 1주차':d<=11?'10월 2주차':d<=18?'10월 3주차':d<=25?'10월 4주차':'10월 5주차'}
function weekTag(name){return {'9월 마지막 주':'티징','10월 1주차':'징안점 소개','10월 2주차':'한국 지점 소개','10월 3주차':'실장 인터뷰 · 정보성','10월 4주차':'실장 인터뷰 · 정보성','10월 5주차':'오픈 사전 안내','11월 1주차':'오픈 홍보'}[name]||''}
function weekLabel(name){return name.split(' ').map(esc).join('<br>')}
function shortDate(value){const m=/^(\d{4})-(\d{2})-(\d{2})$/.exec(value);if(!m)return esc(value||'—');const dt=new Date(Number(m[1]),Number(m[2])-1,Number(m[3]));const day=['일','월','화','수','목','금','토'][dt.getDay()];return Number(m[2])+'/'+Number(m[3])+' ('+day+')'}
function weeklyHTML(records){
 const items=records.filter(x=>x.kind==='캘린더').map(x=>({...x,week:weekName(x.date)}));
 const order=['9월 마지막 주','10월 1주차','10월 2주차','10월 3주차','10월 4주차','10월 5주차','11월 1주차'];
 const groups=order.map((name,i)=>({name,index:i,items:items.filter(x=>x.week===name)})).filter(g=>g.items.length);
 const rows=groups.map(g=>g.items.map((x,i)=>'<tr class="mk-week-'+g.index+'">'+(i===0?'<td class="mk-weekcell" rowspan="'+g.items.length+'"><strong>'+weekLabel(g.name)+'</strong><span>'+esc(weekTag(g.name))+'</span></td>':'')+'<td class="mk-date">'+shortDate(x.date)+'</td><td class="mk-form"><span class="mk-icon '+(x.form==='영상'?'video':'photo')+'">'+(x.form==='영상'?'▶':'▣')+'</span>'+esc(x.form||'—')+'</td><td class="mk-topic">'+esc(x.title||'추후 입력')+'</td><td class="mk-detail">'+esc(x.detail||'추후 입력')+'</td><td class="mk-note"><span>'+esc(x.status||'예정')+'</span></td></tr>').join('')).join('');
 return '<div class="mk-plan-head"><div><p class="eyebrow">중국사업 · 1호점 징안점</p><h2>마케팅 주차별 계획</h2></div><div class="mk-open"><b>11/10 OPEN</b><small>상하이 징안에서 만나는 VELYB</small></div></div><div class="mk-table-wrap"><table class="mk-table"><thead><tr><th>주차</th><th>날짜</th><th>형태</th><th>주제</th><th>상세 내용</th><th>비고</th></tr></thead><tbody>'+rows+'</tbody></table></div>'
}
function meetingHTML(){return '<div class="panel"><h2>마케팅 회의 정리</h2><p><strong>운영 방식</strong> · 주차별 관리, 기본 영상 1건 + 사진 2건</p><p><strong>10월 3~4주차</strong> · 실장 인터뷰 영상 + 정보성 사진 콘텐츠. 인터뷰는 개인 녹화 전달 또는 직접 인터뷰 방식.</p><p><strong>10월 5주차</strong> · 징안점 위치·찾아가는 방법 영상. 현지 업체 직접 촬영 가능 여부 확인.</p><p><strong>11월 1주차</strong> · 오픈 이벤트·사전예약 혜택 등 전환형 콘텐츠 중심. 영리성 콘텐츠 가능 여부에 따라 확정.</p></div>'}
function marketingView(data,item){const records=marketingRecords(data),tabs='<div class="tabs" aria-label="마케팅"><button data-marketing="calendar" aria-pressed="'+(marketingMode==='calendar')+'">캘린더</button><button data-marketing="weekly" aria-pressed="'+(marketingMode==='weekly')+'">주차별 계획</button><button data-marketing="minutes" aria-pressed="'+(marketingMode==='minutes')+'">회의록</button></div>',road=baseProjectView(data,item);const roadmap=road.match(/<section class="panel stage-panel">[\s\S]*?<\/section>/)?.[0]||'';if(marketingMode==='weekly')return tabs+weeklyHTML(records);if(marketingMode==='minutes')return tabs+meetingHTML();return tabs+roadmap+calendarHTML(records,marketingMonth)}
window.marketingSectionHTML=function(data,mode){const source=window.marketingContentSource(data);const records=marketingRecords(source.data);return mode==='weekly'?weeklyHTML(records):mode==='minutes'?meetingHTML():calendarHTML(records,marketingMonth)};
projectView=function(data,item){return item.sheet==='마케팅'?marketingView(data,item):baseProjectView(data,item)};
document.addEventListener('click',e=>{const b=e.target.closest('button[data-marketing],button[data-month]');if(!b)return;if(b.dataset.marketing){marketingMode=b.dataset.marketing;render()}if(b.dataset.month){marketingMonth+=b.dataset.month==='next'?1:-1;if(marketingMonth<9)marketingMonth=11;if(marketingMonth>11)marketingMonth=9;render()}});
const style=document.createElement('style');style.textContent=`
.mcal-head{display:flex;align-items:center;justify-content:center;gap:18px}.mcal-head button{border:1px solid var(--line);background:white;border-radius:8px;padding:6px 14px;font-size:22px}.mcal-week,.mcal-grid{display:grid;grid-template-columns:repeat(7,minmax(0,1fr))}.mcal-week b{text-align:center;padding:10px;background:var(--blue2);border:1px solid var(--line)}.mcal-cell{min-height:125px;background:white;border:1px solid var(--line);padding:8px}.mcal-cell.muted{background:#f4f5f6}.mcal-item{margin-top:7px;padding:7px;border-radius:8px;background:#f7ecef}.mcal-item small,.mcal-item strong{display:block}.mcal-item small{color:var(--muted);font-size:11px}.mcal-item strong{font-size:13px;line-height:1.35}
.mk-plan-head{display:flex;align-items:flex-start;justify-content:space-between;gap:20px;margin:10px 0 18px}.mk-plan-head h2{margin:2px 0 0;font-size:28px}.mk-open{min-width:240px;background:#fff0f5;border:1px solid #f8dbe6;border-radius:14px;padding:14px 18px}.mk-open b,.mk-open small{display:block}.mk-open b{font-size:18px;color:#1f3553}.mk-open small{margin-top:2px;color:var(--muted)}
.mk-table-wrap{overflow:auto;border-radius:12px}.mk-table{width:100%;min-width:1080px;border-collapse:separate;border-spacing:0 7px}.mk-table thead th{background:#354a61;color:#fff;text-align:center;padding:11px 12px;font-size:14px;border-right:1px solid rgba(255,255,255,.22)}.mk-table thead th:first-child{border-radius:9px 0 0 9px}.mk-table thead th:last-child{border-radius:0 9px 9px 0;border-right:0}.mk-table tbody td{background:#fff;border-top:1px solid #e4e8ee;border-bottom:1px solid #e4e8ee;border-right:1px solid #e4e8ee;padding:9px 12px;font-size:14px;vertical-align:middle}.mk-table tbody td:first-child{border-left:1px solid #e4e8ee}.mk-weekcell{width:165px;text-align:left;padding:14px 16px!important;border-radius:10px 0 0 10px}.mk-weekcell strong{display:block;font-size:18px;line-height:1.2}.mk-weekcell span{display:inline-block;margin-top:8px;padding:4px 10px;border-radius:999px;font-size:11px;font-weight:700;background:rgba(255,255,255,.65)}.mk-date{width:95px;text-align:center;white-space:nowrap;font-weight:600;color:#536477}.mk-form{width:110px;white-space:nowrap}.mk-icon{display:inline-flex;width:23px;height:23px;align-items:center;justify-content:center;border-radius:5px;color:#fff;margin-right:7px;font-size:11px;font-weight:700}.mk-icon.photo{background:#ff4f8f}.mk-icon.video{background:#3d7cff}.mk-topic{font-weight:700;color:#152943}.mk-detail{color:#33485f}.mk-note{width:90px;text-align:center}.mk-note span{display:inline-block;min-width:58px;padding:4px 11px;background:#fde9ef;color:#7b4658;border-radius:999px;font-size:12px}.mk-week-0 .mk-weekcell{background:#ffe9ef;color:#c91455}.mk-week-1 .mk-weekcell{background:#e4f2ff;color:#0d4f96}.mk-week-2 .mk-weekcell{background:#e5f7e8;color:#176b4d}.mk-week-3 .mk-weekcell{background:#ebeafe;color:#214d8c}.mk-week-4 .mk-weekcell{background:#ffe7ef;color:#c91455}.mk-week-5 .mk-weekcell{background:#fff3cf;color:#6d4c13}.mk-week-6 .mk-weekcell{background:#dcf7f1;color:#0d685d}.mk-table tbody tr:first-child td:not(.mk-weekcell){border-top-left-radius:0}.mk-table tbody tr td:last-child{border-radius:0 8px 8px 0}
@media(max-width:900px){.mcal-cell{min-height:90px;padding:5px}.mcal-item strong{font-size:11px}.mcal-week b{font-size:12px;padding:6px}.mk-plan-head{display:block}.mk-open{margin-top:12px;min-width:0}.mk-table{min-width:940px}.mk-weekcell{width:145px}.mk-table tbody td{font-size:13px;padding:8px 10px}}
`;document.head.appendChild(style);
})();
