(function(){
let marketingMode='calendar', marketingMonth=new Date().getMonth()+1;
const baseProjectView=projectView;
function marketingRecords(data){if(!data)return[];const h=data.headers;const idx=n=>h.findIndex(x=>String(x).trim()===n);return data.rows.map(r=>({kind:String(r[idx('구분')]||''),order:Number(r[idx('순서')]||999),title:String(r[idx('제목')]||''),detail:String(r[idx('설명')]||''),form:String(r[idx('담당')]||''),date:String(r[idx('마감일')]||''),status:String(r[idx('상태')]||''),show:checked(r[idx('표시')])})).filter(x=>x.show)}
function calendarHTML(records,month){const year=2026,first=new Date(year,month-1,1),last=new Date(year,month,0),start=(first.getDay()+6)%7;let cells='';for(let i=0;i<start;i++)cells+='<div class="mcal-cell muted"></div>';for(let d=1;d<=last.getDate();d++){const iso=year+'-'+String(month).padStart(2,'0')+'-'+String(d).padStart(2,'0'),items=records.filter(x=>x.kind==='캘린더'&&x.date===iso);cells+='<div class="mcal-cell"><b>'+d+'</b>'+items.map(x=>'<div class="mcal-item"><small>'+esc(x.form||'콘텐츠')+'</small><strong>'+esc(x.title)+'</strong></div>').join('')+'</div>'}return '<div class="mcal-head"><button data-month="prev">‹</button><h2>'+year+'년 '+month+'월 콘텐츠 캘린더</h2><button data-month="next">›</button></div><div class="mcal-week">'+['월','화','수','목','금','토','일'].map(x=>'<b>'+x+'</b>').join('')+'</div><div class="mcal-grid">'+cells+'</div>'}
function weeklyHTML(records){const rows=records.filter(x=>x.kind==='캘린더').map(x=>{const m=Number(x.date.slice(5,7)),d=Number(x.date.slice(8,10));let w=m===9?'9월 마지막 주':m===11?'11월 1주차':d<=4?'10월 1주차':d<=11?'10월 2주차':d<=18?'10월 3주차':d<=25?'10월 4주차':'10월 5주차';return[w,x.form,x.title,x.detail,x.status]} );return table(['주차','형태','주제','상세 내용','비고'],rows)}
function meetingHTML(){return '<div class="panel"><h2>마케팅 회의 정리</h2><p><strong>운영 방식</strong> · 주차별 관리, 기본 영상 1건 + 사진 2건</p><p><strong>10월 3~4주차</strong> · 실장 인터뷰 영상 + 정보성 사진 콘텐츠. 인터뷰는 개인 녹화 전달 또는 직접 인터뷰 방식.</p><p><strong>10월 5주차</strong> · 징안점 위치·찾아가는 방법 영상. 현지 업체 직접 촬영 가능 여부 확인.</p><p><strong>11월 1주차</strong> · 오픈 이벤트·사전예약 혜택 등 전환형 콘텐츠 중심. 영리성 콘텐츠 가능 여부에 따라 확정.</p></div>'}
function marketingView(data,item){const records=marketingRecords(data),tabs='<div class="tabs" aria-label="마케팅"><button data-marketing="calendar" aria-pressed="'+(marketingMode==='calendar')+'">캘린더</button><button data-marketing="weekly" aria-pressed="'+(marketingMode==='weekly')+'">주차별 계획</button><button data-marketing="minutes" aria-pressed="'+(marketingMode==='minutes')+'">회의록</button></div>',road=baseProjectView(data,item);const roadmap=road.match(/<section class="panel stage-panel">[\s\S]*?<\/section>/)?.[0]||'';if(marketingMode==='weekly')return tabs+'<div class="section-heading"><div><p class="eyebrow">중국사업 · 1호점 징안점</p><h2>주차별 계획</h2></div></div>'+weeklyHTML(records);if(marketingMode==='minutes')return tabs+meetingHTML();return tabs+roadmap+calendarHTML(records,marketingMonth)}
projectView=function(data,item){return item.sheet==='마케팅'?marketingView(data,item):baseProjectView(data,item)};
document.addEventListener('click',e=>{const b=e.target.closest('button[data-marketing],button[data-month]');if(!b)return;if(b.dataset.marketing){marketingMode=b.dataset.marketing;render()}if(b.dataset.month){marketingMonth+=b.dataset.month==='next'?1:-1;if(marketingMonth<9)marketingMonth=11;if(marketingMonth>11)marketingMonth=9;render()}});
const style=document.createElement('style');style.textContent='.mcal-head{display:flex;align-items:center;justify-content:center;gap:18px}.mcal-head button{border:1px solid var(--line);background:white;border-radius:8px;padding:6px 14px;font-size:22px}.mcal-week,.mcal-grid{display:grid;grid-template-columns:repeat(7,minmax(0,1fr))}.mcal-week b{text-align:center;padding:10px;background:var(--blue2);border:1px solid var(--line)}.mcal-cell{min-height:125px;background:white;border:1px solid var(--line);padding:8px}.mcal-cell.muted{background:#f4f5f6}.mcal-item{margin-top:7px;padding:7px;border-radius:8px;background:#f7ecef}.mcal-item small,.mcal-item strong{display:block}.mcal-item small{color:var(--muted);font-size:11px}.mcal-item strong{font-size:13px;line-height:1.35}@media(max-width:900px){.mcal-cell{min-height:90px;padding:5px}.mcal-item strong{font-size:11px}.mcal-week b{font-size:12px;padding:6px}}';document.head.appendChild(style);
})();