'use strict';
let overviewData=null;
function dateNumber(value){const m=/^(\d{4})-(\d{2})-(\d{2})$/.exec(String(value));if(!m)return null;const n=Date.UTC(+m[1],+m[2]-1,+m[3]);return new Date(n).toISOString().slice(0,10)===value?n:null}
function koreaToday(){const parts=new Intl.DateTimeFormat('en-US',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(new Date());return ['year','month','day'].map(k=>parts.find(p=>p.type===k).value).join('-')}
function dday(target,today=koreaToday()){const a=dateNumber(target),b=dateNumber(today);if(a===null||b===null)return '미설정';const days=Math.round((a-b)/86400000);return days===0?'D-DAY':days>0?'D-'+days:'D+'+Math.abs(days)}
function summarize(data){const counts={완료:0,진행:0,대기:0,이슈:0,기타:0};if(!data||data.error)return {total:0,counts,percent:null};const idx=data.headers.findIndex(h=>['상태','진행상태'].includes(h.trim()));if(idx<0)return{total:data.rows.length,counts,percent:null};for(const row of data.rows){const status=String(row[idx]||'').replace(/\s/g,'');const key=({완료:'완료',진행:'진행',진행중:'진행',대기:'대기',확인대기:'대기',예정:'대기',이슈:'이슈'})[status]||'기타';counts[key]++}return{total:data.rows.length,counts,percent:data.rows.length?Math.round(counts.완료/data.rows.length*100):null}}
function overviewView(){
 const settings=overviewData?.settings||{},events=overviewData?.items||[],today=koreaToday();
 const categories=menus.filter(m=>m.type==='table');const stats=categories.map(m=>({menu:m,summary:summarize(tables[m.sheet])}));
 const totals={완료:0,진행:0,대기:0,이슈:0,기타:0};let total=0,complete=true;
 for(const s of stats){total+=s.summary.total;for(const key of Object.keys(totals))totals[key]+=s.summary.counts[key];if(!tables[s.menu.sheet]||tables[s.menu.sheet].error||(s.summary.total&&s.summary.percent===null))complete=false}
 const percent=complete&&total?Math.round(totals.완료/total*100):null;
 const list=(kind)=>{let items=events.filter(e=>e.kind===kind&&e.text);if(kind==='주요일정')items=items.filter(e=>dateNumber(e.date)===null||e.date>=today).sort((a,b)=>(a.date||'9999').localeCompare(b.date||'9999')||(a.time||'').localeCompare(b.time||''));return items.length?'<ul class="ov-list">'+items.map(e=>'<li><div>'+esc(e.text)+'</div>'+((e.date||e.time)?'<p class="subtle">'+esc(e.date)+' '+esc(e.time||'시간 미정')+'</p>':'')+'</li>').join('')+'</ul>':'<p class="subtle">'+(kind==='주요일정'?'예정된 일정이 없습니다.':'등록된 내용이 없습니다.')+'</p>'};
 const notice=!overviewData?'오버뷰 연결 코드 업데이트 후 시트 내용을 불러옵니다.':overviewData.error;
 return (notice?'<p class="panel">'+esc(notice)+'</p>':'')+'<div class="ov-heading"><strong>'+esc(settings.프로젝트명||'VELYB CHINA BUSINESS')+'</strong><span>중국사업 통합 현황</span></div><div class="ov-top"><section class="panel"><h2>전체 진행률</h2><div class="ov-number">'+(percent===null?'미설정':percent+'%')+'</div><p class="subtle">표시된 업무 분야의 완료 항목 ÷ 전체 항목</p></section><section class="panel ov-open"><h2>OPEN D-DAY</h2><div class="ov-number">'+dday(settings.오픈목표일)+'</div><p>'+esc(settings.오픈목표일||'목표일 미설정')+' · 한국 날짜 기준</p></section></div><div class="ov-counts">'+['완료','진행','대기','이슈'].map(k=>'<div><span>'+k+'</span><strong>'+(complete?totals[k]:'—')+'</strong></div>').join('')+'</div>'+(totals.기타?'<p class="subtle">기타·상태 미입력 '+totals.기타+'건은 전체 항목 수에 포함됩니다.</p>':'')+(!complete?'<p class="subtle">업무 데이터 또는 상태 열을 불러오지 못해 전체 집계를 표시하지 않습니다.</p>':'')+'<div class="ov-columns"><section class="panel"><h2>이번 주 핵심 업무</h2>'+list('핵심업무')+'</section><section class="panel"><h2>주요 일정</h2>'+list('주요일정')+'</section></div><section class="panel ov-progress"><h2>분야별 진행현황</h2>'+stats.map(({menu:m,summary:s})=>{const manual=settings['진행률:'+m.sheet];const parsed=manual!==undefined&&String(manual).trim()!==''?Number(String(manual).replace('%','')):NaN;const isManual=Number.isFinite(parsed)&&parsed>=0&&parsed<=100;const p=isManual?parsed:s.percent;return '<div class="ov-progress-row"><button class="ov-link" data-sheet="'+esc(m.sheet)+'">'+esc(m.name)+'</button><div class="ov-track">'+(p===null?'':'<div style="width:'+p+'%"></div>')+'</div><span>'+(p===null?'미설정':p+'%')+'</span><small>'+ (isManual?'직접 입력':tables[m.sheet]?.error?'연결 오류':p===null?'데이터 입력 전':'완료 기준')+'</small></div>'}).join('')+'</section><section class="panel ov-issues"><h2>주요 이슈 / 의사결정 필요</h2>'+list('이슈')+'</section>';
}
